---
title: "CA_AirQuality_glm"
author: "Emily Scott"
date: "December 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load packages}
library("splines"); library("lme4"); 
library("SpatioTemporal"); library("sp"); library("mgcv") #we need "gam" function
library("ggplot2"); library("knitr"); library("tidyverse"); library("ape") #moran's I
library("spdep"); library("CARBayesST")
```

```{r Load data}
load("./data/dat.R")
```

```{r Define glm function}
# Gaussian distribution
glm_fx <- function(health_outcome)
{
  i.col <- which(colnames(dat) == health_outcome)

  dat$year_center <- scale(dat$year, scale = FALSE)
  q.year <- quantile(dat$year_center, c(0.25, 0.50, 0.75))

  fit <- lmer(unlist(dat[,i.col]) ~ pm25 + ns(year_center, knots = q.year) + age60_perc + est.black.percent + (1|region/county), 
              data = dat)
  
  return(fit)
}

# summary(glm_fx("asthma_young"))    # Asthma in adults 18-39
# summary(glm_fx("asthma_older"))    # COPD or asthma in adults 40+
# 
# summary(glm_fx("amputation_diab")) # Amputation due to diabetes
# summary(glm_fx("diabetes_st"))     # Short-term diabetes complications
# summary(glm_fx("diabetes_lt"))     # Long-term diabetes complications
# summary(glm_fx("diabetes_uc"))     # Uncontrolled diabetes complications
# 
# summary(glm_fx("angina"))          # Angina
# summary(glm_fx("heart_fail"))      # Heart failure
# summary(glm_fx("hypertension"))    # Hypertension
# 
# summary(glm_fx("dehydration"))     # Dehydration
# summary(glm_fx("pneumonia"))       # Pneumonia
# summary(glm_fx("uti"))             # UTI

```

```{r Define interpretation function}
# Take as input the output of glm_fx
interpret_fx <- function(fit)
{
  # Identify outcome variable from fit
  health_outcome <- as.character(names(fit@frame$`unlist(dat[, i.col])`)[1])
  health_outcome <- substr(health_outcome, 1, nchar(health_outcome)-1)

  # Redefine health outcome
  health_outcome <- ifelse(health_outcome == "amputation_diab", "amputation due to diabetes",
                    ifelse(health_outcome == "angina", "angina",
                    ifelse(health_outcome == "asthma_older", "COPD or asthma in older adults (age 40+)",
                    ifelse(health_outcome == "asthma_young", "asthma in younger adults (age 18-39)",
                    ifelse(health_outcome == "dehydration", "dehydration",
                    ifelse(health_outcome == "diabetes_lt", "diabetes long-term complications",
                    ifelse(health_outcome == "diabetes_st", "diabetes short-term complications",
                    ifelse(health_outcome == "diabetes_uc", "uncontrolled diabetes complications",
                    ifelse(health_outcome == "heart_fail", "heart failure", 
                    ifelse(health_outcome == "hypertension", "hypertension",
                    ifelse(health_outcome == "pneumonia", "pneumonia",
                    ifelse(health_outcome == "uti", "UTI",
                           health_outcome))))))))))))
  
  # Identify relevant coefficients
  i.int <- which(rownames(summary(fit)$coefficients) == "(Intercept)")
  i.pm25 <- which(rownames(summary(fit)$coefficients) == "pm25")
  
  # Save coefficient values
  int <- round(summary(fit)$coefficients[i.int,1],2)
  int.se <- round(summary(fit)$coefficients[i.int,2],2)
  pm25 <- round(summary(fit)$coefficients[i.pm25,1],2)
  pm25.se <- round(summary(fit)$coefficients[i.pm25,2],2)
  
  # Interpretation
  interpretation <- paste("The expected hospitalization rate for ", health_outcome, " is ", int, " hospitalizations per 100,000 people at risk when there are zero days over the pm2.5 national standard (95% CI: (", round(int - 1.96*int.se, 2), ", ", round(int + 1.96*int.se,2), ")). For every additional day over the national pm2.5 standard, we expect a ", pm25, " change in this hospitalization rate (95% CI: (", round(pm25 - 1.96*pm25.se, 2), ", ", round(pm25 + 1.96*pm25.se, 2), ")).", sep = "")
  
  return(interpretation)
}

# interpret_fx(glm_fx("asthma_young"))    # Asthma in adults 18-39
# interpret_fx(glm_fx("asthma_older"))    # COPD or asthma in adults 40+
# 
# interpret_fx(glm_fx("amputation_diab")) # Amputation due to diabetes
# interpret_fx(glm_fx("diabetes_st"))     # Short-term diabetes complications
# interpret_fx(glm_fx("diabetes_lt"))     # Long-term diabetes complications
# interpret_fx(glm_fx("diabetes_uc"))     # Uncontrolled diabetes complications
# 
# interpret_fx(glm_fx("angina"))          # Angina
# interpret_fx(glm_fx("heart_fail"))      # Heart failure
# interpret_fx(glm_fx("hypertension"))    # Hypertension
# 
# interpret_fx(glm_fx("dehydration"))     # Dehydration
# interpret_fx(glm_fx("pneumonia"))       # Pneumonia
# interpret_fx(glm_fx("uti"))             # UTI

```

```{r}
plot_fx <- function(health_outcome, x_axis)
{
  # Create centered year variable; calculate quartiles; store unique values in vector
  dat$year_center <- scale(dat$year, scale = FALSE)
  q.year <- quantile(dat$year_center, c(0.25, 0.50, 0.75))
  year_vector <- as.vector(unique(dat$year_center))
  
  # Calculate average value for percent black
  dat <- group_by(dat, county) %>%
    mutate(mean_black_percent = mean(est.black.percent))

  # Calculate spline basis expansion
  m <- model.matrix(~ns(year_vector, knots = q.year))
  m <- as.data.frame(m)
  m$year_center <- year_vector

  # Create dataframe for plotting
  plot_df <- expand.grid(year_center = unique(dat$year_center),
                         pm25 = as.numeric(min(dat$pm25, na.rm = TRUE):max(dat$pm25, na.rm = TRUE)),
                         vars = unique(paste(dat$county, dat$region, 
                                             dat$age60_perc, dat$mean_black_percent, sep = "-"))) 
  
  plot_df <- separate(plot_df, vars, 
                      into = c("county","region","age60_perc","est.black.percent"), 
                      sep = "[-]")
  
  plot_df$age60_perc <- as.numeric(plot_df$age60_perc)
  plot_df$est.black.percent <- as.numeric(plot_df$est.black.percent)

  plot_df <- left_join(plot_df, m, by = "year_center") %>%
    mutate(interaction = paste(county, ":", region, sep = "")) %>%
    filter(interaction %in% rownames(head(ranef(glm_fx(health_outcome)))$`county:region`))
  
  plot_df$Estimate <- predict(glm_fx(health_outcome), plot_df)
  plot_df$Estimate <- ifelse(plot_df$Estimate < 0, 0, plot_df$Estimate)
  plot_df$year <- plot_df$year_center + mean(dat$year)

  # Create labeller 
  region_labels <- c("Coastal", "Farm", "Imperial",
                     "Northern", "San Francisco")
  names(region_labels) <- c("coastal", "farm", "imperial", 
                            "northern", "sanfrancisco")
  
  # Redefine health outcome
  health_outcome <- ifelse(health_outcome == "amputation_diab", "amputation due to diabetes",
                    ifelse(health_outcome == "angina", "angina",
                    ifelse(health_outcome == "asthma_older", "COPD or asthma in older adults (age 40+)",
                    ifelse(health_outcome == "asthma_young", "asthma in younger adults (age 18-39)",
                    ifelse(health_outcome == "dehydration", "dehydration",
                    ifelse(health_outcome == "diabetes_lt", "diabetes long-term complications",
                    ifelse(health_outcome == "diabetes_st", "diabetes short-term complications",
                    ifelse(health_outcome == "diabetes_uc", "uncontrolled diabetes complications",
                    ifelse(health_outcome == "heart_fail", "heart failure", 
                    ifelse(health_outcome == "hypertension", "hypertension",
                    ifelse(health_outcome == "pneumonia", "pneumonia",
                    ifelse(health_outcome == "uti", "UTI",
                           health_outcome))))))))))))

  if (x_axis == "Year" | x_axis == "year")
  {
    plot <- filter(plot_df, pm25 == 0) %>%
      ggplot(aes(x = year, y = Estimate)) +   
      geom_line(aes(color = county)) + 
      facet_grid(~ region, labeller = labeller(region = region_labels)) + 
      ggtitle(paste("Estimated ", health_outcome, " hospitalization rate", sep = "")) +
      xlab("\nYear") +
      ylab("Hospitalizations per 100,000 at risk\n") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90), 
            plot.title = element_text(hjust = 0.5),
            legend.position = "bottom",
            legend.title = element_blank())
  }
  
  if (x_axis == "pm25")
  {
    plot <- filter(plot_df, year == 2012) %>%
      ggplot(aes(x = pm25, y = Estimate)) +
      geom_line(aes(color = county)) + 
      facet_grid(~region, labeller = labeller(region = region_labels)) +
      ggtitle(paste("Estimated ", health_outcome, " hospitalization rate", sep = "")) +
      xlab("\nAnnual number of days over pm2.5 national standard") +
      ylab("Hospitalizations per 100,000 at risk\n") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90), 
            plot.title = element_text(hjust = 0.5),
            legend.position = "bottom",
            legend.title = element_blank())
  }
  return(plot)
}

# plot_fx("asthma_young", "year")    # Asthma in adults 18-39
# plot_fx("asthma_older", "year")    # COPD or asthma in adults 40+
# 
# plot_fx("amputation_diab", "year") # Amputation due to diabetes
# plot_fx("diabetes_st", "year")     # Short-term diabetes complications
# plot_fx("diabetes_lt", "year")     # Long-term diabetes complications
# plot_fx("diabetes_uc", "year")     # Uncontrolled diabetes complications
# 
# plot_fx("angina", "year")          # Angina
# plot_fx("heart_fail", "year")      # Heart failure
# plot_fx("hypertension", "year")    # Hypertension
# 
# plot_fx("dehydration", "year")     # Dehydration
# plot_fx("pneumonia", "year")       # Pneumonia
# plot_fx("uti", "year")             # UTI
# 
# plot_fx("asthma_young", "pm25")    # Asthma in adults 18-39
# plot_fx("asthma_older", "pm25")    # COPD or asthma in adults 40+
# 
# plot_fx("amputation_diab", "pm25") # Amputation due to diabetes
# plot_fx("diabetes_st", "pm25")     # Short-term diabetes complications
# plot_fx("diabetes_lt", "pm25")     # Long-term diabetes complications
# plot_fx("diabetes_uc", "pm25")     # Uncontrolled diabetes complications
# 
# plot_fx("angina", "pm25")          # Angina
# plot_fx("heart_fail", "pm25")      # Heart failure
# plot_fx("hypertension", "pm25")    # Hypertension
# 
# plot_fx("dehydration", "pm25")     # Dehydration
# plot_fx("pneumonia", "pm25")       # Pneumonia
# plot_fx("uti", "pm25")             # UTI

```

```{r Poisson glm}
# Poisson distribution
# glm_fx_poisson <- function(health_outcome)
# {
#   i.col <- which(colnames(dat) == health_outcome)
# 
#   dat$year_center <- scale(dat$year, scale = FALSE)
#   q.year <- quantile(dat$year_center, c(0.25, 0.50, 0.75))
#   
#   dat$age60_center <- scale(dat$age60_perc, scale = FALSE)
#   dat$est.black_center <- scale(dat$est.black.percent, scale = FALSE)
# 
#   fit <- glmer(round(unlist(dat[,i.col])) ~ pm25 + ns(year_center, knots = q.year) + age60_center + est.black_center + (1|region/county), 
#               data = dat, 
#               family = poisson(link = "log"),
#               control = glmerControl(optimizer = "bobyqa",
#                                      optCtrl = list(maxfun = 2e5)))
#   return(fit)
# }

# OFTEN HAS CONVERGENCE ISSUES

# summary(glm_fx_poisson("angina"))
# summary(glm_fx_poisson("asthma_young"))
# summary(glm_fx_poisson("pneumonia"))
# summary(glm_fx_poisson("asthma_older"))
# summary(glm_fx_poisson("diabetes_st"))
# summary(glm_fx_poisson("heart_fail"))
# summary(glm_fx_poisson("hypertension"))
# summary(glm_fx_poisson("diabetes_lt"))
```