---
title: "Something Clever"
author: "Ruthe Huang, Xinye Li, Emily Scott"
date: "December 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, fig.align = "center")
```

## Motivation and Overview

## Related Work

## Initial Questions

## Data

## Exploratory Data Analysis

## Data Analysis

## Narrative and Summary

```{r Read in data, eval = F}
rm(list = ls())
library(tidyverse); library(lubridate); library(stringr); library(rgdal)

# read in 2010-2017 California air quality data
pm25 <- read_csv("data/pm25_annual-days-above-nat-24-hr-stnd.csv", na = "*") %>% group_by(county) %>% summarize(pm2010 = mean(pm2010, na.rm = T), pm2011 = mean(pm2011, na.rm = T), pm2012 = mean(pm2012, na.rm = T), pm2013 = mean(pm2013, na.rm = T), pm2014 = mean(pm2014, na.rm = T), pm2015 = mean(pm2015, na.rm = T), pm2016 = mean(pm2016, na.rm = T), pm2017 = mean(pm2017, na.rm = T)) %>% gather(year, pm25, pm2010:pm2017) %>% mutate(year = as.numeric(str_sub(year, 3, 6))) %>% arrange(county)
head(pm25)

demo <- read_csv("data/age_edu_race.csv")[ , -1] %>% group_by(Geography, Year) %>% summarize(age60_perc = mean(age60_perc, na.rm = T), bachelor_perc = mean(bachelor_perc, na.rm = T), est.white.percent = mean(est.white.percent, na.rm = T), est.black.percent = mean(est.black.percent, na.rm = T)) %>% ungroup() %>% mutate(Geography = str_sub(Geography, 1, -20)) %>% rename(county = Geography, year = Year)
head(demo)

phosp <- read_csv("data/ca-oshpd-preventablehospitalizations-county-2005-2017.csv")
ph_early <- phosp %>% filter(Year < 2016) %>% group_by(County, Year) %>% select(Year, County, PQIDescription, ObsRate_ICD9) %>% spread(PQIDescription, value = ObsRate_ICD9) %>% rename(diabetes_st = "Diabetes Short-term Complications", perf_appendix = "Perforated Appendix", diabetes_lt = "Diabetes Long-term Complications", asthma_older = "COPD or Asthma in Older Adults (Age 40+)", hypertension = "Hypertension", heart_fail = "Heart Failure", dehydration = "Dehydration", pneumonia = "Community-Acquired Pneumonia", uti = "Urinary Tract Infection", angina = "Angina without Procedure", diabetes_uc = "Uncontrolled Diabetes", asthma_young = "Asthma in Younger Adults (Age 18-39)", amputation_diab = "Lower-Extremity Amputation (Diabetes)", pq_overall = "Prevention Quality Overall Composite", pq_acute = "Prevention Quality Acute Composite", pq_chronic = "Prevention Quality Chronic Composite") %>% mutate(pq_diabetes = NA)

ph_late <- phosp %>% filter(Year >= 2016) %>% group_by(County, Year) %>% select(Year, County, PQIDescription, ObsRate_ICD10) %>% spread(PQIDescription, value = ObsRate_ICD10) %>% rename(asthma_older = "COPD or Asthma in Older Adults (Age 40+)", diabetes_st = "Diabetes Short-term Complications", perf_appendix = "Perforated Appendix", diabetes_lt = "Diabetes Long-term Complications", hypertension = "Hypertension", heart_fail = "Heart Failure", dehydration = "Dehydration", pneumonia = "Community-Acquired Pneumonia", uti = "Urinary Tract Infection", diabetes_uc = "Uncontrolled Diabetes", asthma_young = "Asthma in Younger Adults (Age 18-39)", amputation_diab = "Lower-Extremity Amputation (Diabetes)", pq_overall = "Prevention Quality Overall Composite", pq_acute = "Prevention Quality Acute Composite", pq_chronic = "Prevention Quality Chronic Composite", pq_diabetes = "Prevention Quality Diabetes Composite") %>% mutate(angina = NA)

phosp <- rbind(ph_early, ph_late) %>% arrange(County) %>% rename(county = County, year = Year)

dat <- demo %>% left_join(pm25, by = c("county", "year")) %>% left_join(phosp, by = c("county", "year"))
# save(dat, file = "data/dat.Rdata")
rm(list = setdiff(ls(), "dat"))
```

```{r CA visualizations}
rm(list = ls())
library(tidyverse); library(lubridate); library(stringr); library(rgdal)

load("data/dat.Rdata")
cali <- readOGR(dsn = "data/CA_Counties", layer = "CA_Counties_TIGER2016")
plot(cali)

caplot <- function(yr, var) #year: numeric input, var: character input
{
  df <- dat %>% filter(year == yr) %>% select(county, var)
  map <- merge(cali, df, by.x = "NAME", by.y = "county", all.x = T)
  cols <- as.character(cut(map@data[ , var], breaks = quantile(map@data[ , var], seq(0, 1, by = 0.2), na.rm = T), labels = c("darkseagreen1", "mediumspringgreen", "darkturquoise", "dodgerblue2", "navy")))
  
  plot(map, col = "grey77", border = NA, main = paste(var, "by County in", yr))
  plot(map, col = cols, add = T, border = NA)
}

pmplot <- function(yr) # special function for PM 2.5 plots
{
  df <- dat %>% filter(year == yr) %>% select(county, pm25)
  map <- merge(cali, df, by.x = "NAME", by.y = "county", all.x = T)
  cols <- as.character(cut(map@data[ , "pm25"], breaks = c(0, 3, 6, 10, 20, 100), labels = c("darkseagreen1", "mediumspringgreen", "darkturquoise", "dodgerblue2", "navy")))
  
  plot(map, col = "grey77", border = NA, main = paste("Days Over National PM 2.5 Standard by County in", yr))
  plot(map, col = cols, add = T, border = NA)
}
```


```{r, fig.height = 12, fig.width = 8}
par(oma = rep(0, 4), mar = c(0.5, 0.5, 0.8, 0.5), mfrow = c(4, 2))
pmplot(2010)
pmplot(2011)
pmplot(2012)
pmplot(2013)
pmplot(2014)
pmplot(2015)
pmplot(2016)
pmplot(2017)
```

I can't do a legend right now, so mint green is 0-3 days over the national PM 2.5 standard, medium green is <3-6, turquoise is <6-10, cornflower blue is <10-20, and navy is <20-46.


#manipulating Ruthe's data for ST modeling_XL
```{r}
library("SpatioTemporal")
library("sp")

#latitude and longitude
loc = cali@data[,c(5,6,ncol(cali@data)-1,ncol(cali@data))]
loc$NAME = as.character(loc$NAME)
names(loc)[1] = "county"
loc$NAMELSAD = as.character(loc$NAMELSAD)

#xy coordinates using WGS84
#source: https://rpubs.com/dasaptaerwin/19879
xy <- as.data.frame(loc[,c(3,4)])
xy <- as.data.frame(apply(xy,2,function(x){as.numeric(as.character(x))}))
cord.dec = SpatialPoints(cbind(xy$INTPTLON,-xy$INTPTLAT), 
                         proj4string=CRS("+proj=longlat"))
coord <- as.data.frame(spTransform(cord.dec, CRS("+init=epsg:32748")))

#combine latlong and coordinates
loc.all <- data.frame(loc,x = coord$coords.x1, y = coord$coords.x2)

#merge; county as a factor
datnew = left_join(dat,loc.all,by = "county") %>% 
  mutate(ID = factor(county)) %>%
  rename(lat = INTPTLAT, long = INTPTLON)

#outcome data for all categories
outcome_data <- datnew %>%  
  select(-age60_perc,-bachelor_perc,
         -est.white.percent,-est.black.percent,-pm25)

#Let's say we pick dehydration as an outcome
#dehydration only, wide format
#matrix
outcome_dehy <- outcome_data %>% select(ID,year, dehydration) %>%
  spread(key = ID,value = dehydration)

outcome_dehydration <- as.matrix(outcome_dehy[,-1],nrow = 8)
rownames(outcome_dehydration) = c(2010,2011,2012,2013,2014,2015,2016,2017)
colnames(outcome_dehydration) = unique(datnew$county)

#convarites (non-time-varying): I chose 2015 (this may change later)
#data.frame
covariate <- datnew %>% filter(year == 2015)  %>%
  select(ID,x,y,lat,long,age60_perc,bachelor_perc,
         est.white.percent,est.black.percent) %>%
  mutate(type = factor(rep(1,n())))

#check covaraite data is ok
#stCheckCovars(covariate, ID.unique = character(0)) #ok

#time-varying covariate: pm25
#matrix
stcov = datnew %>% select(year,ID,pm25) %>% spread(key = ID,value = pm25)
stcov <- as.matrix(stcov[,-1],nrow = 8)
rownames(stcov) = c(2010,2011,2012,2013,2014,2015,2016,2017)
colnames(stcov) = unique(datnew$county)

#list to create STdata object
st_dehy <- list(obs = outcome_dehydration, X = covariate,
               stcov = stcov)

#STdata Object!
st_dehy_obj <- createSTdata(st_dehy$obs, st_dehy$X, 
                            SpatioTemporal = list(st_pm2.5 = stcov))
# plot(st_dehy_obj,"loc")
# print(st_dehy_obj)

#try to create a STmodel: not working
LUR <- list(~est.black.percent + age60_perc + bachelor_perc)
ST <- "pm25"
locations <- list(coords = c("x","y"), long.lat = c("long", "lat"),others = "type")
cov.beta <- list(covf = "exp", nugget = FALSE)
cov.nu <- list(covf = "exp", nugget = ~type, random.effect = FALSE)
createSTmodel(st_dehy_obj, LUR = LUR, ST = ST, cov.beta = cov.beta, 
              cov.nu = cov.nu, locations = locations)


```








